/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  theme: {
    colors: {
      background: "var(--background)",
      foreground: "var(--foreground)",
      black: "#070A0D",
      white: "#FFFFFF",
      inherit: "inherit",
      current: "currentColor",
      transparent: "transparent",
      fill: {
        component: "var(--fill-component)",
        disabled: "var(--fill-disabled)",
        page: "var(--fill-page)",
      },
      stroke: {
        DEFAULT: "var(--stroke)",
        focus: "var(--stroke-focus)",
        underline: {
          DEFAULT: "var(--stroke-underline)",
          disabled: "var(--stroke-underline-disabled)",
          hover: "var(--stroke-underline-hover)",
        },
      },
      content: {
        disabled: "var(--content-disabled)",
        inverse: "var(--content-inverse)",
        pale: "var(--content-pale)",
        strong: "var(--content-strong)",
        subtle: "var(--content-subtle)",
      },
      primary: {
        DEFAULT: "var(--primary)",
        foreground: "var(--primary-foreground)",
        disabled: "var(--primary-disabled)",
        hover: "var(--primary-hover)",
        pale: "var(--primary-pale)",
        palest: "var(--primary-palest)",
        pressed: "var(--primary-pressed)",
        strong: "var(--primary-strong)",
      },
      secondary: {
        disabled: "var(--secondary-disabled)",
        hover: "var(--secondary-hover)",
        pale: "var(--secondary-pale)",
        palest: "var(--secondary-palest)",
        pressed: "var(--secondary-pressed)",
        strong: "var(--secondary-strong)",
      },
      neutral: {
        pale: "var(--neutral-pale)",
        palest: "var(--neutral-palest)",
      },
      error: {
        DEFAULT: "var(--error)",
        disabled: "var(--error-disabled)",
        hover: "var(--error-hover)",
        pale: "var(--error-pale)",
        palest: "var(--error-palest)",
        pressed: "var(--error-pressed)",
        strong: "var(--error-strong)",
      },
      info: {
        DEFAULT: "var(--info)",
        pale: "var(--info-pale)",
        palest: "var(--info-palest)",
        strong: "var(--info-strong)",
      },
      success: {
        DEFAULT: "var(--success)",
        pale: "var(--success-pale)",
        palest: "var(--success-palest)",
        strong: "var(--success-strong)",
      },
      warning: {
        DEFAULT: "var(--warning)",
        pale: "var(--warning-pale)",
        palest: "var(--warning-palest)",
        strong: "var(--warning-strong)",
      },
      // tip: remove to use default Tailwind colors
      gray: {
        50: "#FBFCFD",
        100: "#F8FAFC",
        200: "#F1F5F9",
        300: "#E2E8F0",
        400: "#CBD5E1",
        500: "#94A3B8",
        600: "#64748B",
        700: "#334155",
        800: "#222C3A",
        900: "#12171F",
      },

      indigo: {
        100: "#EBECF7",
        200: "#D7D8EF",
        300: "#B0B2DF",
        400: "#7478C8",
        500: "#393EB0",
        600: "#343A98",
        700: "#2E3488",
        800: "#282D76",
        900: "#1D2055",
      },
      teal: {
        100: "#ECF5F6",
        200: "#B7D8DB",
        300: "#83BABF",
        400: "#519BA2",
        500: "#1F7B84",
        600: "#196A72",
        700: "#13585F",
        800: "#0E464C",
        900: "#0A3438",
      },

      red: {
        100: "#FFEDED",
        200: "#FEB3B3",
        300: "#FA7C7C",
        400: "#F44747",
        500: "#EB1414",
        600: "#CA0E0E",
        700: "#A90909",
        800: "#860505",
        900: "#620202",
      },
      blue: {
        100: "#E0F2FE",
        200: "#BAE6FD",
        500: "#0EA5E9",
        700: "#0369A1",
        800: "#075985",
      },
      green: {
        100: "#DCFCE7",
        200: "#BBF7D0",
        500: "#22C55E",
        700: "#15803d",
        800: "#166534",
      },
      yellow: {
        100: "#FEF3C7",
        200: "#FDE68A",
        500: "#EAB308",
        700: "#C17D23",
        800: "#9F6313",
      },
    },
    extend: {
      fontSize: {
        "3xl": ["30px", "42px"],
        "2xl": ["24px", "33.6px"],
        xl: ["20px", "28px"],
        lg: ["18px", "25.2px"],
        m: ["16px", "22.4px"],
        sm: ["14px", "19.6px"],
        xs: ["12px", "16.8px"],
        xxs: ["10px", "14px"],
      },
      screens: {
        sm: "640px",
        md: "768px",
        lg: "1024px",
        xl: "1280px",
        "2xl": "1536px",
        "3xl": "1792px",
      },
      container: {
        center: true,
        padding: {
          DEFAULT: "1rem",
          sm: "2rem",
          lg: "4rem",
          xl: "5rem",
          "2xl": "6rem",
        },
      },
    },
  },
  plugins: [
    require("@tailwindcss/forms"),
    require("@tailwindcss/typography"),
    require("tailwindcss-animate"),
  ],
};
